### ISSUE TITLE
The google drive link For downloading the cleaned and labeled portion (only) of CLEAR is blocked

### ISSUE THREAD

**Issue by detectRecog** [ElvishElvis/Continual-Learning#1]
Hello, I'm currently a PhD student from USTC and I'm interested in CL. I have applied to access the link `https://drive.google.com/file/d/1xj5DCYr502SlvoF0INCL1n-gbxi0Kr3v/view?usp=sharing`. Could you please help give the authorization?

**Comment by ElvishElvis** [comment]
Thank you for the interest in the CLEAR dataset! The CLEAR10 dataset is not open to download for now(for upcoming CVPR workshop). Please ask for download permission through google drive and we will notify you through email once we make it public again.( FYI it will be very soon :)
